### ISSUE TITLE
create db about

### ISSUE THREAD

**Issue by erelbi** [Ali-aqrabawi/django-ansible#1]
Hello,
We want to install a server with dnsgo via ansible. But we couldn't run the library. Need to create two tables in models py? Could you please send us some more descriptive installation documents?

**Comment by Ali-aqrabawi** [comment]
please check `README.md` and follow the `Quick Start` guide, you don't need to create the tables your self, all you need to do is to `makemigrations` and then `migrate` and the tables will be created for you.

**Comment by indraabrata** [comment]
try use command python manage.py makemigrations dj_ansible sir, it works for me
