### ISSUE TITLE
when try to execute , got an error object has no attribute '_stats'

### ISSUE THREAD

**Issue by indraabrata** [Ali-aqrabawi/django-ansible#2]
Sir, please help, i want use ur library, but when i try to execute the playbook , the output look like this

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/brot/projectta/env/lib/python3.6/site-packages/dj_ansible/ansible_kit/executor.py", line 136, in execute
    stats = tqm._stats
AttributeError: 'NoneType' object has no attribute '_stats'

I will be very grateful if you help me

**Comment by Ali-aqrabawi** [comment]
i think you have `ansible > 2.7`
please make sure to use `ansible= 2.7.10`, you can do `pip3 install ansible==2.7.10`
in addition to that there was a bug in my code so i fixed it, so also make sure to download the new version `pip install django-ansible==1.0.3` 

let me know if it did not work.

**Comment by indraabrata** [comment]
well its work sir, but can i ask why i got failed result on operating system IOS, im using ios_command got failed, please help , this is the last i ask

![please bisa](https://user-images.githubusercontent.com/45393115/79199615-70f02280-7e5f-11ea-86bd-e5ebb29ebebe.png)

**Comment by Ali-aqrabawi** [comment]
if you use `ansible` playbook directly (without `django-ansible`) does it work? this should be related to `Asnible` itself.

**Comment by indraabrata** [comment]
now it works sir , your django-ansible  Thankyou very much
![image](https://user-images.githubusercontent.com/45393115/79379575-4b5f3800-7f89-11ea-82ec-e00fad9b1b73.png)
